//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StitchingShop
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Windows;
    
    public partial class Customer : BusinessModel
    {
        public static readonly DependencyProperty CustomerIDProperty = DependencyProperty.Register("CustomerID", typeof(int), typeof(Customer), new PropertyMetadata());
        public static readonly DependencyProperty CustomerNameProperty = DependencyProperty.Register("CustomerName", typeof(string), typeof(Customer), new PropertyMetadata());
        public static readonly DependencyProperty CustomerImageProperty = DependencyProperty.Register("CustomerImage", typeof(byte[]), typeof(Customer), new PropertyMetadata());
        public static readonly DependencyProperty CNICProperty = DependencyProperty.Register("CNIC", typeof(string), typeof(Customer), new PropertyMetadata());
        public static readonly DependencyProperty AddressProperty = DependencyProperty.Register("Address", typeof(string), typeof(Customer), new PropertyMetadata());
    
        public static readonly DependencyProperty PhoneNumbersProperty = DependencyProperty.Register("PhoneNumbers", typeof(ObservableCollection<PhoneNumber>), typeof(Customer), new PropertyMetadata());
        public static readonly DependencyProperty SizeFieldValuesProperty = DependencyProperty.Register("SizeFieldValues", typeof(ObservableCollection<SizeFieldValue>), typeof(Customer), new PropertyMetadata());
        public Customer()
        {
            this.PhoneNumbers = new ObservableCollection<PhoneNumber>();
            this.SizeFieldValues = new ObservableCollection<SizeFieldValue>();
        }
    
        public int CustomerID
    	{
    		get
    		{
    			return (int)this.GetValue(CustomerIDProperty);
    		}
    		set
    		{
    			this.SetValue(CustomerIDProperty, value);
    		}
    	}
        public string CustomerName
    	{
    		get
    		{
    			return (string)this.GetValue(CustomerNameProperty);
    		}
    		set
    		{
    			this.SetValue(CustomerNameProperty, value);
    		}
    	}
        public byte[] CustomerImage
    	{
    		get
    		{
    			return (byte[])this.GetValue(CustomerImageProperty);
    		}
    		set
    		{
    			this.SetValue(CustomerImageProperty, value);
    		}
    	}
        public string CNIC
    	{
    		get
    		{
    			return (string)this.GetValue(CNICProperty);
    		}
    		set
    		{
    			this.SetValue(CNICProperty, value);
    		}
    	}
        public string Address
    	{
    		get
    		{
    			return (string)this.GetValue(AddressProperty);
    		}
    		set
    		{
    			this.SetValue(AddressProperty, value);
    		}
    	}
    
        public virtual ObservableCollection<PhoneNumber> PhoneNumbers
    	{
    		get
    		{
    			return (ObservableCollection<PhoneNumber>)this.GetValue(PhoneNumbersProperty);
    		}
    		set
    		{
    			this.SetValue(PhoneNumbersProperty, value);
    		}
    	}
        public virtual ObservableCollection<SizeFieldValue> SizeFieldValues
    	{
    		get
    		{
    			return (ObservableCollection<SizeFieldValue>)this.GetValue(SizeFieldValuesProperty);
    		}
    		set
    		{
    			this.SetValue(SizeFieldValuesProperty, value);
    		}
    	}
    }
}
