//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StitchingShop
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Windows;
    
    public partial class Design : BusinessModel
    {
        public static readonly DependencyProperty DesignIDProperty = DependencyProperty.Register("DesignID", typeof(int), typeof(Design), new PropertyMetadata());
        public static readonly DependencyProperty DesignNameProperty = DependencyProperty.Register("DesignName", typeof(string), typeof(Design), new PropertyMetadata());
        public static readonly DependencyProperty DesignTypeIDProperty = DependencyProperty.Register("DesignTypeID", typeof(int), typeof(Design), new PropertyMetadata());
        public static readonly DependencyProperty DesignImageProperty = DependencyProperty.Register("DesignImage", typeof(byte[]), typeof(Design), new PropertyMetadata());
    
        public static readonly DependencyProperty DesignTypeProperty = DependencyProperty.Register("DesignType", typeof(DesignType), typeof(Design), new PropertyMetadata());
        public static readonly DependencyProperty SizeFieldsProperty = DependencyProperty.Register("SizeFields", typeof(ObservableCollection<SizeField>), typeof(Design), new PropertyMetadata());
        public Design()
        {
            this.SizeFields = new ObservableCollection<SizeField>();
        }
    
        public int DesignID
    	{
    		get
    		{
    			return (int)this.GetValue(DesignIDProperty);
    		}
    		set
    		{
    			this.SetValue(DesignIDProperty, value);
    		}
    	}
        public string DesignName
    	{
    		get
    		{
    			return (string)this.GetValue(DesignNameProperty);
    		}
    		set
    		{
    			this.SetValue(DesignNameProperty, value);
    		}
    	}
        public int DesignTypeID
    	{
    		get
    		{
    			return (int)this.GetValue(DesignTypeIDProperty);
    		}
    		set
    		{
    			this.SetValue(DesignTypeIDProperty, value);
    		}
    	}
        public byte[] DesignImage
    	{
    		get
    		{
    			return (byte[])this.GetValue(DesignImageProperty);
    		}
    		set
    		{
    			this.SetValue(DesignImageProperty, value);
    		}
    	}
    
        public virtual DesignType DesignType
    	{
    		get
    		{
    			return (DesignType)this.GetValue(DesignTypeProperty);
    		}
    		set
    		{
    			this.SetValue(DesignTypeProperty, value);
    		}
    	}
        public virtual ObservableCollection<SizeField> SizeFields
    	{
    		get
    		{
    			return (ObservableCollection<SizeField>)this.GetValue(SizeFieldsProperty);
    		}
    		set
    		{
    			this.SetValue(SizeFieldsProperty, value);
    		}
    	}
    }
}
