//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StitchingShop
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Windows;
    
    public partial class PhoneNumber : BusinessModel
    {
        public static readonly DependencyProperty CustomerIDProperty = DependencyProperty.Register("CustomerID", typeof(int), typeof(PhoneNumber), new PropertyMetadata());
        public static readonly DependencyProperty NumberProperty = DependencyProperty.Register("Number", typeof(string), typeof(PhoneNumber), new PropertyMetadata());
    
        public static readonly DependencyProperty CustomerProperty = DependencyProperty.Register("Customer", typeof(Customer), typeof(PhoneNumber), new PropertyMetadata());
        public int CustomerID
    	{
    		get
    		{
    			return (int)this.GetValue(CustomerIDProperty);
    		}
    		set
    		{
    			this.SetValue(CustomerIDProperty, value);
    		}
    	}
        public string Number
    	{
    		get
    		{
    			return (string)this.GetValue(NumberProperty);
    		}
    		set
    		{
    			this.SetValue(NumberProperty, value);
    		}
    	}
    
        public virtual Customer Customer
    	{
    		get
    		{
    			return (Customer)this.GetValue(CustomerProperty);
    		}
    		set
    		{
    			this.SetValue(CustomerProperty, value);
    		}
    	}
    }
}
