//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StitchingShop
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Windows;
    
    public partial class SizeField : BusinessModel
    {
        public static readonly DependencyProperty SizeFieldIDProperty = DependencyProperty.Register("SizeFieldID", typeof(int), typeof(SizeField), new PropertyMetadata());
        public static readonly DependencyProperty SizeFieldNameEnglishProperty = DependencyProperty.Register("SizeFieldNameEnglish", typeof(string), typeof(SizeField), new PropertyMetadata());
        public static readonly DependencyProperty SizeFieldNameUrduProperty = DependencyProperty.Register("SizeFieldNameUrdu", typeof(string), typeof(SizeField), new PropertyMetadata());
    
        public static readonly DependencyProperty SizeFieldValuesProperty = DependencyProperty.Register("SizeFieldValues", typeof(ObservableCollection<SizeFieldValue>), typeof(SizeField), new PropertyMetadata());
        public static readonly DependencyProperty DesignsProperty = DependencyProperty.Register("Designs", typeof(ObservableCollection<Design>), typeof(SizeField), new PropertyMetadata());
        public static readonly DependencyProperty DesignTypesProperty = DependencyProperty.Register("DesignTypes", typeof(ObservableCollection<DesignType>), typeof(SizeField), new PropertyMetadata());
        public SizeField()
        {
            this.SizeFieldValues = new ObservableCollection<SizeFieldValue>();
            this.Designs = new ObservableCollection<Design>();
            this.DesignTypes = new ObservableCollection<DesignType>();
        }
    
        public int SizeFieldID
    	{
    		get
    		{
    			return (int)this.GetValue(SizeFieldIDProperty);
    		}
    		set
    		{
    			this.SetValue(SizeFieldIDProperty, value);
    		}
    	}
        public string SizeFieldNameEnglish
    	{
    		get
    		{
    			return (string)this.GetValue(SizeFieldNameEnglishProperty);
    		}
    		set
    		{
    			this.SetValue(SizeFieldNameEnglishProperty, value);
    		}
    	}
        public string SizeFieldNameUrdu
    	{
    		get
    		{
    			return (string)this.GetValue(SizeFieldNameUrduProperty);
    		}
    		set
    		{
    			this.SetValue(SizeFieldNameUrduProperty, value);
    		}
    	}
    
        public virtual ObservableCollection<SizeFieldValue> SizeFieldValues
    	{
    		get
    		{
    			return (ObservableCollection<SizeFieldValue>)this.GetValue(SizeFieldValuesProperty);
    		}
    		set
    		{
    			this.SetValue(SizeFieldValuesProperty, value);
    		}
    	}
        public virtual ObservableCollection<Design> Designs
    	{
    		get
    		{
    			return (ObservableCollection<Design>)this.GetValue(DesignsProperty);
    		}
    		set
    		{
    			this.SetValue(DesignsProperty, value);
    		}
    	}
        public virtual ObservableCollection<DesignType> DesignTypes
    	{
    		get
    		{
    			return (ObservableCollection<DesignType>)this.GetValue(DesignTypesProperty);
    		}
    		set
    		{
    			this.SetValue(DesignTypesProperty, value);
    		}
    	}
    }
}
