//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StitchingShop
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Windows;
    
    public partial class SizeFieldValue : BusinessModel
    {
        public static readonly DependencyProperty SizeFieldIDProperty = DependencyProperty.Register("SizeFieldID", typeof(int), typeof(SizeFieldValue), new PropertyMetadata());
        public static readonly DependencyProperty CustomerIDProperty = DependencyProperty.Register("CustomerID", typeof(int), typeof(SizeFieldValue), new PropertyMetadata());
        public static readonly DependencyProperty ValueProperty = DependencyProperty.Register("Value", typeof(double), typeof(SizeFieldValue), new PropertyMetadata());
    
        public static readonly DependencyProperty CustomerProperty = DependencyProperty.Register("Customer", typeof(Customer), typeof(SizeFieldValue), new PropertyMetadata());
        public static readonly DependencyProperty SizeFieldProperty = DependencyProperty.Register("SizeField", typeof(SizeField), typeof(SizeFieldValue), new PropertyMetadata());
        public int SizeFieldID
    	{
    		get
    		{
    			return (int)this.GetValue(SizeFieldIDProperty);
    		}
    		set
    		{
    			this.SetValue(SizeFieldIDProperty, value);
    		}
    	}
        public int CustomerID
    	{
    		get
    		{
    			return (int)this.GetValue(CustomerIDProperty);
    		}
    		set
    		{
    			this.SetValue(CustomerIDProperty, value);
    		}
    	}
        public double Value
    	{
    		get
    		{
    			return (double)this.GetValue(ValueProperty);
    		}
    		set
    		{
    			this.SetValue(ValueProperty, value);
    		}
    	}
    
        public virtual Customer Customer
    	{
    		get
    		{
    			return (Customer)this.GetValue(CustomerProperty);
    		}
    		set
    		{
    			this.SetValue(CustomerProperty, value);
    		}
    	}
        public virtual SizeField SizeField
    	{
    		get
    		{
    			return (SizeField)this.GetValue(SizeFieldProperty);
    		}
    		set
    		{
    			this.SetValue(SizeFieldProperty, value);
    		}
    	}
    }
}
